
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compiladores.AnalizadorSintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENORIGQ = 43;
  public static final int STRING_LITERAL = 62;
  public static final int CHAR = 60;
  public static final int CONST = 17;
  public static final int PACKED = 34;
  public static final int CHAR_LITERAL = 65;
  public static final int IMPRIMIR = 61;
  public static final int MENORQ = 42;
  public static final int ENTERO = 63;
  public static final int XOR = 48;
  public static final int RESTA = 3;
  public static final int CONTINUE = 69;
  public static final int INT = 56;
  public static final int RANGO = 14;
  public static final int ARRAY = 36;
  public static final int FOR = 26;
  public static final int MATCH = 24;
  public static final int NOT = 49;
  public static final int AND = 47;
  public static final int IGUAL = 10;
  public static final int RECORD = 35;
  public static final int TYPE = 30;
  public static final int OR = 46;
  public static final int BOOL = 59;
  public static final int DOBP = 9;
  public static final int DIV = 4;
  public static final int BEGIN = 32;
  public static final int SUMA = 2;
  public static final int UMENOS = 6;
  public static final int IF = 23;
  public static final int ID = 66;
  public static final int DECRE = 51;
  public static final int OF = 31;
  public static final int DECIMAL = 64;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int TRUE = 18;
  public static final int PROGRAM = 39;
  public static final int error = 1;
  public static final int COMA = 12;
  public static final int CADENA = 57;
  public static final int MOD = 21;
  public static final int BREAK = 68;
  public static final int REAL = 58;
  public static final int POTENCIA = 20;
  public static final int MAYORIGQ = 45;
  public static final int ELSE = 29;
  public static final int PUNTO = 13;
  public static final int MAYORQ = 44;
  public static final int IGUALIGUAL = 40;
  public static final int TO = 38;
  public static final int WHILE = 25;
  public static final int DEFAULT = 22;
  public static final int INCRE = 50;
  public static final int THEN = 37;
  public static final int LEER = 67;
  public static final int END = 33;
  public static final int MULTI = 5;
  public static final int PARC = 8;
  public static final int PARA = 7;
  public static final int CORC = 55;
  public static final int CORA = 54;
  public static final int FALSE = 19;
  public static final int CIERRE = 11;
  public static final int LLAVEC = 53;
  public static final int DIFIGUAL = 41;
  public static final int LLAVEA = 52;
  public static final int VAR = 16;
  public static final int DO = 27;
  public static final int SUBRANGO = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "DIV",
  "MULTI",
  "UMENOS",
  "PARA",
  "PARC",
  "DOBP",
  "IGUAL",
  "CIERRE",
  "COMA",
  "PUNTO",
  "RANGO",
  "SUBRANGO",
  "VAR",
  "CONST",
  "TRUE",
  "FALSE",
  "POTENCIA",
  "MOD",
  "DEFAULT",
  "IF",
  "MATCH",
  "WHILE",
  "FOR",
  "DO",
  "RETURN",
  "ELSE",
  "TYPE",
  "OF",
  "BEGIN",
  "END",
  "PACKED",
  "RECORD",
  "ARRAY",
  "THEN",
  "TO",
  "PROGRAM",
  "IGUALIGUAL",
  "DIFIGUAL",
  "MENORQ",
  "MENORIGQ",
  "MAYORQ",
  "MAYORIGQ",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "INCRE",
  "DECRE",
  "LLAVEA",
  "LLAVEC",
  "CORA",
  "CORC",
  "INT",
  "CADENA",
  "REAL",
  "BOOL",
  "CHAR",
  "IMPRIMIR",
  "STRING_LITERAL",
  "ENTERO",
  "DECIMAL",
  "CHAR_LITERAL",
  "ID",
  "LEER",
  "BREAK",
  "CONTINUE"
  };
}

